namespace abap.analyzer;

using { cuid, managed } from '@sap/cds/common';

/**
 * Cache of custom ABAP objects fetched from On-Premise
 * Refreshed periodically or on-demand
 */
entity CustomObjects : cuid, managed {
    objectName      : String(120)   @title: 'Object Name';
    objectType      : String(10)    @title: 'Object Type';
    objectTypeText  : String(100)   @title: 'Type Description';
    category        : String(30)    @title: 'Category';
    subType         : String(1)     @title: 'Sub Type';
    package         : String(30)    @title: 'Package';
    createdByAbap   : String(12)    @title: 'ABAP Created By';
    createdOnAbap   : Date          @title: 'ABAP Created On';
    changedByAbap   : String(12)    @title: 'ABAP Changed By';
    changedOnAbap   : Date          @title: 'ABAP Changed On';
    lineCount       : Integer       @title: 'Line Count';
    lastSynced      : Timestamp     @title: 'Last Synced';
}

/**
 * Audit log for document generation requests
 */
entity DocumentGenerationLog : cuid, managed {
    objectName      : String(120)   @title: 'Object Name';
    objectType      : String(30)    @title: 'Object Type';
    documentType    : String(10)    @title: 'Document Type (PDF/DOCX)';
    templateUsed    : String(50)    @title: 'Template Used';
    claudeModel     : String(50)    @title: 'Claude Model Used';
    tokensUsed      : Integer       @title: 'Tokens Used';
    generationTime  : Integer       @title: 'Generation Time (ms)';
    status          : String(20)    @title: 'Status';
    errorMessage    : String(500)   @title: 'Error Message';
    generatedBy     : String(100)   @title: 'Generated By';
    generatedAt     : Timestamp     @title: 'Generated At';
}

/**
 * Document templates for BRD generation
 */
entity DocumentTemplates : cuid, managed {
    templateName    : String(100)   @title: 'Template Name';
    templateType    : String(20)    @title: 'Template Type';  // BRD, FUNC_SPEC, TECH_SPEC
    description     : String(500)   @title: 'Description';
    promptTemplate  : LargeString   @title: 'Claude Prompt Template';
    sections        : LargeString   @title: 'Document Sections (JSON)';
    isActive        : Boolean       @title: 'Active';
}

